---

- name: set facts
  set_fact:
    gcloud: 'gcloud --format json --project {{ GOOGLE_CLOUD_PROJECT }}'

- name: set the gcloud account
  command: gcloud config set account {{ GOOGLE_CLOUD_ACCOUNT }}

- name: check current cluster_node
  command: >
    {{ gcloud }}
    container clusters describe {{ CLUSTER_NAME }}
    --zone {{ ZONE }}
  register: cluster_check
  ignore_errors: yes
  failed_when: false

- debug: var=cluster_check

- name: create container cluster
  command: >
    {{ gcloud }}
    container clusters create {{ CLUSTER_NAME }}
    --zone {{ ZONE }}
    --num-nodes={{ CLUSTER_NODE_COUNT }}
    --machine-type={{ MACHINE_TYPE }}
    --enable-autoscaling --min-nodes {{ MIN_NODE_COUNT }} --max-nodes {{ MAX_NODE_COUNT }}
    --enable-cloud-logging
    --enable-cloud-monitoring
    --scopes cloud-platform,projecthosting,storage-rw
  register: cluster_create
  when: cluster_check | failed

- debug: var=cluster_create
